# Generated by Django 2.0.4 on 2018-05-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180522_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
